### ISSUE TITLE
specs_default_work

### ISSUE THREAD

**Issue by Pontuzz** [roccosette/Screeps#1]
Heya, im not sure if it's me being nooby but when i run the scripts i get a reference error

ReferenceError: specs_default_work is not defined
    at _init:139:45
    at eval:250:4
    at Object.i:6:22415
    at main:6:1
    at eval:67:4
    at Object.i:6:22415
    at Object.c.runCode:7:407

Most likely i missed something in the init file but im not experienced enough to realize what :o

**Comment by roccosette** [comment]
For the first run, the first loop, and every when you make change, you need to put Memory.init to 1, and after put again to 0, is for optimize CPU.

**Comment by Pontuzz** [comment]
Ohh now i see, Lol i feel kind of silly now haha. Thanks for your quick response
